### ISSUE TITLE
run.py I meet an error

### ISSUE THREAD

**Issue by AI-CHN** [time-series-foundation-models/lag-llama#109]
FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\australian_elect
ricity_demand\\metadata.json'

**Comment by AI-CHN** [comment]
Encountered the following problem when running the script file pretrain.sh:

**Comment by AI-CHN** [comment]
Encountered the following problem when running the script file pretrain.sh:       FileNotFoundError: [Errno 2] No such file or directory: 'datasets\australian_elect ricity_demand\metadata.json'  and  the previous successful output statements were         
wandb:  View run at https://wandb.ai/252424970-null/lag-llama-test/runs/44a7795e
Context length: 32 Prediction Length: 1 max(lags_seq): 1092 Therefore, window size: 1125

**Comment by AI-CHN** [comment]
The details of this error are                                                                                                                                                                        Traceback (most recent call last):
  File "D:\ppy\lag-llama-main\run.py", line 842, in <module>
    train(args)
  File "D:\ppy\lag-llama-main\run.py", line 333, in train
    ) = create_train_and_val_datasets_with_dates(
  File "D:\ppy\lag-llama-main\data\data_utils.py", line 173, in create_train_and_val_datasets_with_dates
    raw_dataset = get_dataset(name, path=Path(dataset_path))
  File "D:\anaconda3\envs\llama-lag\lib\site-packages\gluonts\dataset\repository\datasets.py", line 368, in get_dataset      
    return load_datasets(
  File "D:\anaconda3\envs\llama-lag\lib\site-packages\gluonts\dataset\common.py", line 455, in load_datasets
    meta = MetaData.parse_file(Path(metadata) / "metadata.json")
  File "D:\anaconda3\envs\llama-lag\lib\site-packages\pydantic\v1\main.py", line 561, in parse_file
    obj = load_file(
  File "D:\anaconda3\envs\llama-lag\lib\site-packages\pydantic\v1\parse.py", line 57, in load_file
    b = path.read_bytes()
  File "D:\anaconda3\envs\llama-lag\lib\pathlib.py", line 1126, in read_bytes
    with self.open(mode='rb') as f:
  File "D:\anaconda3\envs\llama-lag\lib\pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: 'datasets\\australian_electricity_demand\\metadata.json'

**Comment by kashif** [comment]
could you fix your issue? it could be that the data was not downloaded properly.
